// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LogServiceClient is the client API for LogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogServiceClient interface {
	CreateLogLine(ctx context.Context, in *LogLine, opts ...grpc.CallOption) (*LogLine, error)
	CreateBatchLogLine(ctx context.Context, in *LogLines, opts ...grpc.CallOption) (*LogLines, error)
	GetAllHistory(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*LogLines, error)
	GetLogCount(ctx context.Context, in *LogLines, opts ...grpc.CallOption) (*Count, error)
	GetLogById(ctx context.Context, in *LogLineById, opts ...grpc.CallOption) (*LogLine, error)
}

type logServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLogServiceClient(cc grpc.ClientConnInterface) LogServiceClient {
	return &logServiceClient{cc}
}

func (c *logServiceClient) CreateLogLine(ctx context.Context, in *LogLine, opts ...grpc.CallOption) (*LogLine, error) {
	out := new(LogLine)
	err := c.cc.Invoke(ctx, "/v1.LogService/CreateLogLine", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) CreateBatchLogLine(ctx context.Context, in *LogLines, opts ...grpc.CallOption) (*LogLines, error) {
	out := new(LogLines)
	err := c.cc.Invoke(ctx, "/v1.LogService/CreateBatchLogLine", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) GetAllHistory(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*LogLines, error) {
	out := new(LogLines)
	err := c.cc.Invoke(ctx, "/v1.LogService/GetAllHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) GetLogCount(ctx context.Context, in *LogLines, opts ...grpc.CallOption) (*Count, error) {
	out := new(Count)
	err := c.cc.Invoke(ctx, "/v1.LogService/GetLogCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) GetLogById(ctx context.Context, in *LogLineById, opts ...grpc.CallOption) (*LogLine, error) {
	out := new(LogLine)
	err := c.cc.Invoke(ctx, "/v1.LogService/GetLogById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogServiceServer is the server API for LogService service.
// All implementations must embed UnimplementedLogServiceServer
// for forward compatibility
type LogServiceServer interface {
	CreateLogLine(context.Context, *LogLine) (*LogLine, error)
	CreateBatchLogLine(context.Context, *LogLines) (*LogLines, error)
	GetAllHistory(context.Context, *emptypb.Empty) (*LogLines, error)
	GetLogCount(context.Context, *LogLines) (*Count, error)
	GetLogById(context.Context, *LogLineById) (*LogLine, error)
	mustEmbedUnimplementedLogServiceServer()
}

// UnimplementedLogServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLogServiceServer struct {
}

func (UnimplementedLogServiceServer) CreateLogLine(context.Context, *LogLine) (*LogLine, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLogLine not implemented")
}
func (UnimplementedLogServiceServer) CreateBatchLogLine(context.Context, *LogLines) (*LogLines, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBatchLogLine not implemented")
}
func (UnimplementedLogServiceServer) GetAllHistory(context.Context, *emptypb.Empty) (*LogLines, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllHistory not implemented")
}
func (UnimplementedLogServiceServer) GetLogCount(context.Context, *LogLines) (*Count, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLogCount not implemented")
}
func (UnimplementedLogServiceServer) GetLogById(context.Context, *LogLineById) (*LogLine, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLogById not implemented")
}
func (UnimplementedLogServiceServer) mustEmbedUnimplementedLogServiceServer() {}

// UnsafeLogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogServiceServer will
// result in compilation errors.
type UnsafeLogServiceServer interface {
	mustEmbedUnimplementedLogServiceServer()
}

func RegisterLogServiceServer(s grpc.ServiceRegistrar, srv LogServiceServer) {
	s.RegisterService(&LogService_ServiceDesc, srv)
}

func _LogService_CreateLogLine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogLine)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).CreateLogLine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.LogService/CreateLogLine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).CreateLogLine(ctx, req.(*LogLine))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_CreateBatchLogLine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogLines)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).CreateBatchLogLine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.LogService/CreateBatchLogLine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).CreateBatchLogLine(ctx, req.(*LogLines))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_GetAllHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).GetAllHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.LogService/GetAllHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).GetAllHistory(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_GetLogCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogLines)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).GetLogCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.LogService/GetLogCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).GetLogCount(ctx, req.(*LogLines))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_GetLogById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogLineById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).GetLogById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.LogService/GetLogById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).GetLogById(ctx, req.(*LogLineById))
	}
	return interceptor(ctx, in, info, handler)
}

// LogService_ServiceDesc is the grpc.ServiceDesc for LogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.LogService",
	HandlerType: (*LogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLogLine",
			Handler:    _LogService_CreateLogLine_Handler,
		},
		{
			MethodName: "CreateBatchLogLine",
			Handler:    _LogService_CreateBatchLogLine_Handler,
		},
		{
			MethodName: "GetAllHistory",
			Handler:    _LogService_GetAllHistory_Handler,
		},
		{
			MethodName: "GetLogCount",
			Handler:    _LogService_GetLogCount_Handler,
		},
		{
			MethodName: "GetLogById",
			Handler:    _LogService_GetLogById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/v1/log.proto",
}
